spring:
  liquibase.contexts: '!test'

  application:
    name: Books API

  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

  datasource:
    url: jdbc:mysql://localhost:3306/library?useSSL=false
    username: library
    password: library

  server:
    port: 8080
    contextPath: /